Add changeset to modules
N-Patarov/bgsite_official pull request #20
Opened 2021-03-09 16:16 UTC by ykostov

WIP, do not merge

2021-03-09 19:50 UTC, rmilushev requested changes
We have to generate a migration for the join table `website_tag` like this:
```
mix ecto.gen.migration add_website_tag_table websites:references tag:references
```

2021-03-09 19:50 UTC, rmilushev commented on lib/bgsite_official/categories/tag.ex
> +  def changeset_update_projects(%Tag{} = tags, attrs) do
I think the name should not include `projects`, but something like `changeset_update_tags_for_websites`.

2021-03-09 19:50 UTC, rmilushev commented on lib/bgsite_official/categories/tag.ex
> +      join_through: "website_project",
The join table (when created) will be `website_tag`, not `.._project`. We will generate a migration for the join table.

2021-03-09 19:50 UTC, rmilushev commented on lib/bgsite_official/categories/tag.ex
> +      Website,
The [module name](https://github.com/N-Patarov/bgsite_official/pull/20/files) is `Websites`.

2021-03-10 09:59 UTC, ykostov commented
:+1:

2021-03-10 09:59 UTC, closed without merging