Many to many associations`
N-Patarov/bgsite_official pull request #24
Opened 2021-03-10 09:59 UTC by ykostov

2021-03-10 10:11 UTC, rmilushev requested changes
We will refactor the function for website -> tags association.

2021-03-10 10:11 UTC, rmilushev commented on lib/bgsite_official/categories/tag.ex
> +     Website,
The module name is : `defmodule BgsiteOfficial.Home.Websites do`

2021-03-10 10:11 UTC, rmilushev commented on lib/bgsite_official/home/websites.ex
> +    join_through: "tag_website",
The join table name is `website_tag`, please change it.

2021-03-10 10:11 UTC, rmilushev commented on lib/bgsite_official/home/websites.ex
> +      {:ok, Accounts.get_tag(tag.id)}
IMO `Accounts` is not proper here, check, please.

2021-03-21 13:27 UTC, ykostov commented
New pull for this

2021-03-21 13:27 UTC, closed without merging